# Generated by Django 4.1.7 on 2023-05-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rename_email_from_contactus_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-id']},
        ),
    ]
