# Generated by Django 4.1.7 on 2023-03-28 10:41

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_rate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.avatar_path),
        ),
    ]
