# Generated by Django 4.1.7 on 2023-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
