# Generated by Django 4.1.7 on 2023-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='city',
            field=models.CharField(max_length=64),
        ),
    ]
