# Generated by Django 4.1.7 on 2023-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_source_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[('CURRENCY_USD', 'Dollar'), ('CURRENCY_EUR', 'Euro')]),
        ),
    ]
