# Generated by Django 4.1.7 on 2023-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_requestresponselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='Anonymous', max_length=128),
        ),
    ]
