# Generated by Django 4.1.7 on 2023-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_contactus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
